# RECUERDEN NO IGNORAR ESTE ARCHIVO, O NO LES PODREMOS CORREGIR.
DIAS_COMPETENCIA = 6
POPULARIDAD_MINIMA_DELEGACION = 0
PROBABILIDAD_ACCIDENTARSE_GIMNASIA = 0.3
# COMPLETAR...
PUNTOS_ENTRENAMIENTO = 5
NIVEL_IMPLEMENTOS = 0.3
PUNTAJE_MINIMO = 0

# parametros deportistas
VELOCIDAD_MINIMA = 0
RESISTENCIA_MINIMA = 0
FLEXIBILIDAD_MINIMA = 0
MORAL_MINIMA = 0
VELOCIDAD_MAXIMA = 100
RESISTENCIA_MAXIMA = 100
FLEXIBILIDAD_MAXIMA = 100
MORAL_MAXIMA = 100

# parametros delegacion
AUMENTO_EXCELENCIA_POR_MEDALLA = 0.01
AUMENTO_MORAL_POR_ENTRENAMIENTO = 1
PORCENTAJE_AUMENTO_IMPLEMENTOS_POR_TECNOLOGIA = 0.1

MORAL_MINIMA_DELEGACION = 0
MORAL_MAXIMA_DELEGACION = 100
FORTALEZA_MINIMA = 0.0
FORTALEZA_MAXIMA = 1.0
MORAL_NECESARIA_FICHAR_DEPORTISTA = 20
# costos acciones delegacion
COSTO_ENTRENAR_DEPORTISTA = 30
COSTO_SANAR_LESIONES = 30
COSTO_COMPRAR_TECNOLOGÏA = 20
COSTO_HABILIDAD_ESPECIAL = 20
# variables en formulas
PROBABILIDAD_MAX_SANAR_LESIONES = 1
PROBABILIDAD_MIN_SANAR_LESIONES = 0
DIVISOR_FORMULA_SANAR_LESIONES = 200
# parametros IEEsparta
PONDERADOR_ENTRENAMIENTO_IEEE = 1.7
EXCELENCIA_MINIMA_IEEE = 0.4
EXCELENCIA_MAXIMA_IEEE = 0.8
IMPLEMENTOS_DEPORTIVOS_MINIMOS = 0.3
IMPLEMENTOS_DEPORTIVOS_MAXIMOS = 0.7
IMPLEMENTOS_MEDICOS_MINIMOS = 0.2
IMPLEMENTOS_MEDICOS_MAXIMOS = 0.6
# paramteros DCCrotona
EXCELENCIA_MINIMA_IEEE = 0.3
EXCELENCIA_MAXIMA_IEEE = 0.7
IMPLEMENTOS_DEPORTIVOS_MINIMOS = 0.2
IMPLEMENTOS_DEPORTIVOS_MAXIMOS = 0.6
IMPLEMENTOS_MEDICOS_MINIMOS = 0.4
IMPLEMENTOS_MEDICOS_MAXIMOS = 0.8
