# RECUERDEN NO IGNORAR ESTE ARCHIVO, O NO LES PODREMOS CORREGIR.
DIAS_COMPETENCIA = 6
POPULARIDAD_MINIMA_DELEGACION = 0
PROBABILIDAD_ACCIDENTARSE_GIMNASIA = 0.3
# COMPLETAR...
PUNTOS_ENTRENAMIENTO = 5
NIVEL_IMPLEMENTOS = 0.3
PUNTAJE_MINIMO = 0
