# RECUERDEN NO IGNORAR ESTE ARCHIVO, O NO LES PODREMOS CORREGIR.
DIAS_COMPETENCIA = 6
POPULARIDAD_MINIMA_DELEGACION = 0
PROBABILIDAD_ACCIDENTARSE_GIMNASIA = 0.3
# COMPLETAR...
PUNTOS_ENTRENAMIENTO = 5
NIVEL_IMPLEMENTOS = 0.3
PUNTAJE_MINIMO = 0

# parametros deportistas
VELOCIDAD_MINIMA = 0
RESISTENCIA_MINIMA = 0
FLEXIBILIDAD_MINIMA = 0
MORAL_MINIMA = 0
VELOCIDAD_MAXIMA = 100
RESISTENCIA_MAXIMA = 100
FLEXIBILIDAD_MAXIMA = 100
MORAL_MAXIMA = 100
